x = linspace(0,1,1000);
subplot(2,1,1);
hold on;
y = sin(5*x);
plot(x,y);
y=cos(5*x);
plot(x,y);
axis([0 1 -2 2]);
title('y=sin(5x) und y=cos(5x)');
xlabel('x');
ylabel('y');
grid on;
subplot(2,1,2);
x = linspace(-3,3,1000);
y = sin(exp(x));
plot(x,y);
title('y=sin(exp(x))');
xlabel('x');
ylabel('y');
